Repository newrelic/nri-jmx, pull requests merged in 2019-02, with the labels that each got.

#30 Added license files
  .papers_config.yml
  papers_manifest.yml
Labels: risk:none

#32 Add suffix for selecting yml while packaging
  Makefile-package.mk
Labels: bug

#34 Added Dockerfile
  Dockerfile
Labels: enhancement, risk:none
