Repository newrelic/nri-jmx, pull requests merged in 2019-11, with the labels that each got.

#47 SDK update
  CHANGELOG.md
  src/jmx.go
  src/request.go
  vendor/github.com/newrelic/infra-integrations-sdk/jmx/jmx.go
  vendor/vendor.json
Labels: enhancement, risk:low

#48 embed nrjmx tool on windows
  .gitignore
  CHANGELOG.md
  pkg/windows/nri-386-installer/Product.wxs.template
  pkg/windows/nri-amd64-installer/Product.wxs.template
  src/jmx.go
Labels: enhancement, risk:low

#49 Set up nrjmx version dependency
  Makefile-package.mk
Labels: enhancement, risk:low

#51 Depend on nrjmx 1.5.2 instead of 1.5.0
  Makefile-package.mk
Labels: bug, risk:low

#52 Bean patter error displays correct pattern
  src/request.go
Labels: enhancement, risk:none
